version: '3'
services:
  validator-alice:
    image: parity/polkadot:master-0.8.22-cdb5c40-a1443153
    ports:
      - '30333:30333'
      - '9944:9944'
      - '9933:9933'
    volumes:
      - ./:/data
    entrypoint:
      - polkadot
      - --chain=/data/docker/dex_raw.json
      - --base-path=/data/alice_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.1
        aliases:
          - alice

  validator-bob:
    image: parity/polkadot:master-0.8.22-cdb5c40-a1443153
    ports:
      - '30335:30333'
      - '9966:9944'
      - '9955:9933'
    volumes:
      - ./:/data
    entrypoint:
      - polkadot
      - --chain=/data/docker/dex_raw.json
      - --base-path=/data/bob_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.2
        aliases:
          - bob
  
  validator-charlie:
    image: parity/polkadot:master-0.8.22-cdb5c40-a1443153
    ports:
      - '30337:30333'
      - '9988:9944'
      - '9977:9933'
    volumes:
      - ./:/data
    entrypoint:
      - polkadot
      - --chain=/data/docker/dex_raw.json
      - --base-path=/data/charlie_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --charlie
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.4
        aliases:
          - charlie

  validator-dave:
    image: parity/polkadot:master-0.8.22-cdb5c40-a1443153
    ports:
      - '30339:30333'
      - '9922:9944'
      - '9911:9933'
    volumes:
      - ./:/data
    entrypoint:
      - polkadot
      - --chain=/data/docker/dex_raw.json
      - --base-path=/data/dave_data
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --dave
      - --no-prometheus
      - --no-telemetry
    networks:
      dex_net:
        ipv4_address: 172.28.1.6
        aliases:
          - dave

  dex-genesis-state:
    image: belsyuen/dex-collator:v0.1.0
    volumes:
      - dex-genesis-state:/data
    command: >
      /usr/bin/dex-chain
      export-genesis-state
      /data/dex-genesis-state

  dex-collator:
    image: belsyuen/dex-collator:v0.1.0
    volumes:
      - ./:/data
    depends_on:
      - validator-alice
      - validator-bob
      - validator-charlie
      - validator-dave
    command: >
      /usr/bin/start_dex_collator.sh
    networks:
      dex_net:
        ipv4_address: 172.28.1.8
        aliases:
          - collator

  dex-runtime:
    image: belsyuen/dex-runtime:v0.1.0
    volumes:
      - dex-chain-wasm-runtime:/runtime


  registrar:
    image: belsyuen/dex-registrar:v0.1.0
    volumes:
      - dex-genesis-state:/dex-genesis-state
      - dex-chain-wasm-runtime:/dex-chain-wasm-runtime
    depends_on:
      - validator-alice
      - dex-runtime
      - dex-genesis-state
    networks:
      dex_net:

volumes:
  dex-genesis-state:
  dex-chain-wasm-runtime:

networks:
  dex_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  