version: '3'
services:
  validator-alice:
    image: chevdor/polkadot:0.8.14
    ports:
      - '30333:30333'
      - '9944:9944'
      - '9933:9933'
    volumes:
      - ./:/polkadot/.local/share/polkadot/
    entrypoint:
      - polkadot
      - --chain=/polkadot/.local/share/polkadot/ddex_raw.json
      - --base-path=/polkadot/.local/share/polkadot/validator_alice
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
  validator-bob:
    image: chevdor/polkadot:0.8.14
    ports:
      - '30330:30330'
      - '9966:9966'
      - '9955:9955'
    volumes:
      - ./:/polkadot/.local/share/polkadot/
    entrypoint:
      - polkadot
      - --chain=/polkadot/.local/share/polkadot/ddex_raw.json
      - --base-path=/polkadot/.local/share/polkadot/validator_bob
      - --port=30330
      - --ws-port=9966
      - --rpc-port=9955
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
  paraA:
    image: chevdor/polkadot:0.8.14
    ports:
      - '30330:30330'
      - '9966:9966'
      - '9955:9955'
    volumes:
      - ./:/polkadot/.local/share/polkadot/
    entrypoint:
      - polkadot
      - --chain=/polkadot/.local/share/polkadot/ddex_raw.json
      - --base-path=/polkadot/.local/share/polkadot/validator_bob
      - --port=30330
      - --ws-port=9966
      - --rpc-port=9955
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
    
