version: '3'
services:
  validator-alice:
    image: chevdor/polkadot:0.8.14
    ports:
      - '30333:30333'
      - '9944:9944'
      - '9933:9933'
    volumes:
      - ./:/data
    entrypoint:
      - polkadot
      - --chain=/data/ddex_raw.json
      - --base-path=/data/validator_alice
      - --port=30333
      - --ws-port=9944
      - --rpc-port=9933
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --alice
      - --no-prometheus
      - --no-telemetry

  validator-bob:
    image: chevdor/polkadot:0.8.14
    ports:
      - '30335:30335'
      - '9922:9922'
      - '9911:9911'
    volumes:
       - ./:/data

    entrypoint:
      - polkadot
      - --chain=/data/ddex_raw.json
      - --base-path=/data/validator_bob
      - --port=30335
      - --ws-port=9922
      - --rpc-port=9911
      - --rpc-cors=all
      - --unsafe-rpc-external
      - --unsafe-ws-external
      - --validator
      - --bob
      - --no-prometheus
      - --no-telemetry

          